name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/chrissargent/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: myimage
          path: /tmp/myimage.tar
          
  incontainer:
    runs-on: ubuntu-latest
    needs: docker
    container: ghcr.io/chrissargent/app:latest
    steps:
      - run: |
          docker run ghcr.io/chrissargent/app:latest
          yarn start
        name: Run in container